@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jonh Doe ",
  "email": "jonhdoe@gmail.com",
  "password": "123456"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "jonhdoe@gmail.com",
  "password": "123456"
}


###

# @name user-profile
GET {{baseUrl}}/me
Authorization: Bearer {{authToken}}

###

# @name get_orders
GET {{baseUrl}}/orders
Authorization: Bearer {{authToken}}

###

# @name create-orders
POST {{baseUrl}}/orders
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "items": [
    {
      "productId": "cm8ok937f0001vyp0pdvuqwqw",
      "quantity": 7
    }
  ]
}

###

# @name get-order-details
GET {{baseUrl}}/orders/cm8ok938a000bvyp07tjvmu41
Authorization: Bearer {{authToken}}